### ISSUE TITLE
Make `Canvas::draw` generic by using `IntoQuad` trait

### ISSUE THREAD

**Issue by hecrj** [hecrj/coffee#21]
I apparently forgot to update this method.

**Comment by 5t0n3** [comment]
Since the [`into_quad`](https://github.com/hecrj/coffee/blob/56ff3b4e992013b2438cf3b9c46fd5cf606e9d13/src/graphics/quad.rs#L45) method from the `IntoQuad` trait requires `x_unit` and `y_unit` parameters, were you planning on adding those to  [`Canvas::draw`](https://github.com/hecrj/coffee/blob/56ff3b4e992013b2438cf3b9c46fd5cf606e9d13/src/graphics/canvas.rs#L68) as parameters?

**Comment by hecrj** [comment]
@5t0n3 We should be able to use the [`width`](https://github.com/hecrj/coffee/blob/master/src/graphics/canvas.rs#L37) and [`height`](https://github.com/hecrj/coffee/blob/master/src/graphics/canvas.rs#L44) methods, like we do on [`Image:.draw`](https://github.com/hecrj/coffee/blob/master/src/graphics/image.rs#L107).

Thank you for looking into this!
