### ISSUE TITLE
Errors running examples, when using coffee as a dependency.

### ISSUE THREAD

**Issue by tonis2** [hecrj/coffee#38]
First of all thanks for all the hard work and `coffee` is rad, but i would like to report something i found.

When i am trying to run the examples from https://github.com/hecrj/coffee/tree/master/examples

But instead of cloning the repository and then running them, i am using `coffee` as a dependency.

I am adding `coffee` to `Cargo.toml` like this. 
```
[dependencies]
coffee = { version = "0.2", features = ["vulkan"] }
```
When i now copy the examples and try to run them, i get trait mismatch errors in all examples,
for example such.

```rust
 --> src/main.rs:36:5
   |
36 |     fn draw(&self, view: &mut Self::View, frame: &mut Frame, _timer: &Timer) {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `coffee::graphics::window::Window`, found struct `coffee::graphics::window::frame::Frame`
   |
   = note: expected type `fn(&Colors, &mut View, &mut coffee::graphics::window::Window, &coffee::timer::Timer)`
              found type `fn(&Colors, &mut View, &mut coffee::graphics::window::frame::Frame<'_>, &coffee::timer::Timer)`

```

**Comment by hecrj** [comment]
The current `master` branch has breaking changes since the `0.2` release. You should be able to run the examples from the `0.2.0` tag: https://github.com/hecrj/coffee/tree/0.2.0/examples

I understand this may be confusing and we might change it once we release `0.3.0`. However, I like to push changes to `master` instead of developing in a non-default branch, specially now that we are starting, because it makes the project look not dead.

**Comment by tonis2** [comment]
Okay i understand, no problem, will close the ticket.
